import Head from 'next/head'
import Image from 'next/image'



export default function Home() {
  return (
    <div>
      <Head>
        <title>Dimitri Marco Portfolio</title>
        <meta name="deescription" content="Generated by skipper"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main>
        <section className='bg-blue-700 min-h-screen'>
          <h1>hello</h1>
        </section>
      </main>
    </div>
    
  )
}
