import Head from 'next/head'
import { BsFillMoonStarsFill } from "react-icons/bs";




export default function Home() {
  return (
    <div>
      <Head>
        <title>Dimitri Marco Portfolio</title>
        <meta name="deescription" content="Generated by skipper"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className='bg-white px-10'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl'>developedbyskipper</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill className='cursor-pointer text-2xl' />
              </li>
              <li>
                <a href="#" className='bg-cyan-500 text-white px-4 py-2 rounded-full'>Resume</a>
              </li>
            </ul>
          </nav>
        </section>
      </main>
    </div>
    
  )
}
